# Generated by Django 6.0.6 on 2026-07-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emil',
            new_name='email',
        ),
    ]
